export type FeeTier = "low" | "medium" | "high";

export type RussiaFeeUniversity = {
  id: string;
  name: string;
  cityLabel: string;
  location: string;
  population: string;
  distanceMoscow: string;
  byAir: string;
  established: string;
  tuition: string;
  hostel: string;
  other: string;
  description?: string;
  bullets: string[];
  detailHref?: string;
};

export const LOW_TUITION_UNIVERSITIES: RussiaFeeUniversity[] = [
  {
    id: "ingush",
    name: "Ingush State University",
    cityLabel: "Magas",
    location: "Magas",
    population: "1,00,000 below",
    distanceMoscow: "1,800 km",
    byAir: "~3 hours",
    established: "1994",
    tuition: "2,00,000 RUB/year",
    hostel: "25,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Ingush State University is a public university established in 1994, located in Magas. It offers MBBS in Russia for Indian students at low cost, making it a popular choice for affordable MBBS abroad. The university provides basic laboratories and clinical training in affiliated hospitals, ensuring practical exposure. The campus is peaceful, safe, and suitable for international students. Hostel facilities are secure, comfortable, and budget-friendly.",
    bullets: [
      "Location: Magas",
      "Population: 1,00,000 below",
      "Distance from Moscow: 1,800 km",
      "By Air: ~3 hours",
      "Established: 1994",
      "Tuition Fees: 2,00,000 RUB/year",
      "Hostel Fees: 25,000 RUB/year",
      "Other Charges (Visa + Medical + Biometric): 25,000 RUB/year",
    ],
    detailHref: "/study-destinations/study-mbbs-in-russia/ingush-state-university",
  },
  {
    id: "chuvash",
    name: "Chuvash State University",
    cityLabel: "Cheboksary",
    location: "Cheboksary",
    population: "5,00,000 approx",
    distanceMoscow: "650 km",
    byAir: "~1.5 hours",
    established: "1967",
    tuition: "2,65,000 RUB/year",
    hostel: "81,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Chuvash State University, established in 1967, is a reputed government university offering MBBS in Russia in English medium. It is known for quality medical education abroad with modern labs and strong hospital affiliations for clinical training. The university provides a safe, student-friendly environment and well-maintained hostels for international students.",
    bullets: [
      "Location: Cheboksary",
      "Population: 5,00,000 approx",
      "Distance from Moscow: 650 km",
      "By Air: ~1.5 hours",
      "Established: 1967",
      "Tuition Fees: 2,65,000 RUB/year",
      "Hostel Fees: 81,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
    detailHref: "/study-destinations/study-mbbs-in-russia/chuvash-state-university",
  },
  {
    id: "chita",
    name: "Chita State Medical University",
    cityLabel: "Chita",
    location: "Chita",
    population: "3,50,000 approx",
    distanceMoscow: "6,200 km",
    byAir: "~7–8 hours",
    established: "1953",
    tuition: "2,80,000 RUB/year",
    hostel: "60,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Chita State Medical University, founded in 1953, is a specialized institution offering MBBS abroad at affordable fees. It provides advanced laboratory facilities and strong hospital-based clinical training, making it ideal for students seeking practical medical education in Russia. Hostel facilities are available, and the campus is safe for international students.",
    bullets: [
      "Location: Chita",
      "Population: 3,50,000 approx",
      "Distance from Moscow: 6,200 km",
      "By Air: ~7–8 hours",
      "Established: 1953",
      "Tuition Fees: 2,80,000 RUB/year",
      "Hostel Fees: 60,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "syktyvkar",
    name: "Syktyvkar State University",
    cityLabel: "Syktyvkar",
    location: "Syktyvkar",
    population: "2,50,000 approx",
    distanceMoscow: "1,300 km",
    byAir: "~2 hours",
    established: "1972",
    tuition: "2,82,760 RUB/year",
    hostel: "20,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Established in 1972, Syktyvkar State University offers low-cost MBBS in Russia with a focus on academic learning and clinical exposure through local hospitals. It is a good option for students looking for budget MBBS abroad. Hostel facilities are simple, safe, and economical.",
    bullets: [
      "Location: Syktyvkar",
      "Population: 2,50,000 approx",
      "Distance from Moscow: 1,300 km",
      "By Air: ~2 hours",
      "Established: 1972",
      "Tuition Fees: 2,82,760 RUB/year",
      "Hostel Fees: 20,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "sevastopol",
    name: "Sevastopol State University",
    cityLabel: "Sevastopol",
    location: "Sevastopol",
    population: "5,00,000 approx",
    distanceMoscow: "1,800 km",
    byAir: "~3 hours",
    established: "2014",
    tuition: "2,87,000 RUB/year",
    hostel: "70,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Sevastopol State University, established in 2014, is a modern university offering MBBS in Russia for international students. It provides updated laboratories and clinical training in city hospitals, ensuring hands-on experience. The university offers well-equipped hostels and a comfortable environment for students studying MBBS abroad.",
    bullets: [
      "Location: Sevastopol",
      "Population: 5,00,000 approx",
      "Distance from Moscow: 1,800 km",
      "By Air: ~3 hours",
      "Established: 2014",
      "Tuition Fees: 2,87,000 RUB/year",
      "Hostel Fees: 70,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "kemerovo-su",
    name: "Kemerovo State University",
    cityLabel: "Kemerovo",
    location: "Kemerovo",
    population: "5,50,000 approx",
    distanceMoscow: "3,600 km",
    byAir: "~4.5 hours",
    established: "1973",
    tuition: "2,99,000 RUB/year",
    hostel: "25,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Kemerovo State University, founded in 1973, is a well-known institution offering affordable MBBS in Russia. It provides good academic support, laboratory facilities, and clinical exposure through regional hospitals. The campus is safe, and hostel facilities are economical and suitable for international students.",
    bullets: [
      "Location: Kemerovo",
      "Population: 5,50,000 approx",
      "Distance from Moscow: 3,600 km",
      "By Air: ~4.5 hours",
      "Established: 1973",
      "Tuition Fees: 2,99,000 RUB/year",
      "Hostel Fees: 25,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
    detailHref: "/study-destinations/study-mbbs-in-russia/kemorovo-state-university",
  },
  {
    id: "krasnoyarsk",
    name: "Krasnoyarsk State Medical University",
    cityLabel: "Krasnoyarsk",
    location: "Krasnoyarsk",
    population: "10,00,000+",
    distanceMoscow: "4,100 km",
    byAir: "~5 hours",
    established: "1942",
    tuition: "3,19,000 RUB/year",
    hostel: "12,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Established in 1942, Krasnoyarsk State Medical University is a leading institution offering high-quality MBBS in Russia. It features advanced labs and strong hospital affiliations for clinical training, making it ideal for students seeking globally recognized medical education. Hostel facilities are affordable and well-maintained.",
    bullets: [
      "Location: Krasnoyarsk",
      "Population: 10,00,000+",
      "Distance from Moscow: 4,100 km",
      "By Air: ~5 hours",
      "Established: 1942",
      "Tuition Fees: 3,19,000 RUB/year",
      "Hostel Fees: 12,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
    detailHref: "/study-destinations/study-mbbs-in-russia/krasnoyarsk-state-medical-university",
  },
  {
    id: "kabardino",
    name: "Kabardino-Balkarian State Medical University",
    cityLabel: "Nalchik",
    location: "Nalchik",
    population: "2,50,000 approx",
    distanceMoscow: "1,500 km",
    byAir: "~2.5 hours",
    established: "1957",
    tuition: "3,24,000 RUB/year",
    hostel: "16,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Kabardino-Balkarian State Medical University, established in 1957, offers MBBS in Russia at reasonable cost. It provides strong clinical exposure through teaching hospitals along with good laboratory facilities. The campus is safe, and hostels are affordable for international students.",
    bullets: [
      "Location: Nalchik",
      "Population: 2,50,000 approx",
      "Distance from Moscow: 1,500 km",
      "By Air: ~2.5 hours",
      "Established: 1957",
      "Tuition Fees: 3,24,000 RUB/year",
      "Hostel Fees: 16,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "amur",
    name: "Amur State Medical University",
    cityLabel: "Blagoveshchensk",
    location: "Blagoveshchensk",
    population: "2,30,000 approx",
    distanceMoscow: "7,800 km",
    byAir: "~8–9 hours",
    established: "1952",
    tuition: "3,25,000 RUB/year",
    hostel: "24,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Amur State Medical University, founded in 1952, is a government medical university offering MBBS abroad at low fees. It provides well-equipped laboratories and hospital-based clinical training, ensuring practical knowledge. Hostel facilities are available, and the environment is safe for international students.",
    bullets: [
      "Location: Blagoveshchensk",
      "Population: 2,30,000 approx",
      "Distance from Moscow: 7,800 km",
      "By Air: ~8–9 hours",
      "Established: 1952",
      "Tuition Fees: 3,25,000 RUB/year",
      "Hostel Fees: 24,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "omsk",
    name: "Omsk State Medical University",
    cityLabel: "Omsk",
    location: "Omsk",
    population: "10,00,000+",
    distanceMoscow: "2,700 km",
    byAir: "~3.5 hours",
    established: "1920",
    tuition: "3,30,000 RUB/year",
    hostel: "20,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Omsk State Medical University, established in 1920, is one of the oldest institutions offering MBBS in Russia for Indian students. It provides excellent clinical exposure through affiliated hospitals and modern laboratories. Hostels are well-developed, and the campus ensures a safe and supportive environment.",
    bullets: [
      "Location: Omsk",
      "Population: 10,00,000+",
      "Distance from Moscow: 2,700 km",
      "By Air: ~3.5 hours",
      "Established: 1920",
      "Tuition Fees: 3,30,000 RUB/year",
      "Hostel Fees: 20,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "petrozavodsk",
    name: "Petrozavodsk State University",
    cityLabel: "Petrozavodsk",
    location: "Petrozavodsk",
    population: "2,80,000 approx",
    distanceMoscow: "1,000 km",
    byAir: "1.5–2 hours",
    established: "1940",
    tuition: "3,45,000 RUB/year",
    hostel: "21,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Petrozavodsk State University, established in 1940, is a reputed institution offering MBBS in Russia at affordable fees. It provides good academic infrastructure, laboratories, and clinical exposure through affiliated hospitals. The environment is safe and suitable for international students, with comfortable hostel facilities.",
    bullets: [
      "Location: Petrozavodsk",
      "Population: 2,80,000 approx",
      "Distance from Moscow: 1,000 km",
      "By Air: 1.5–2 hours",
      "Established: 1940",
      "Tuition Fees: 3,45,000 RUB/year",
      "Hostel Fees: 21,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
    detailHref: "/study-destinations/study-mbbs-in-russia/petrozavodsk-state-university",
  },
  {
    id: "ikbfu",
    name: "Immanuel Kant Baltic Federal University",
    cityLabel: "Kaliningrad",
    location: "Kaliningrad",
    population: "5,00,000 approx",
    distanceMoscow: "1,200 km",
    byAir: "2 hours",
    established: "1947",
    tuition: "3,47,380 RUB/year",
    hostel: "20,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Immanuel Kant Baltic Federal University, founded in 1947, is a modern federal university offering MBBS in Russia for international students. It features advanced labs and hospital-based clinical training, with a European-style campus. Hostels are well-maintained and student-friendly.",
    bullets: [
      "Location: Kaliningrad",
      "Population: 5,00,000 approx",
      "Distance from Moscow: 1,200 km",
      "By Air: 2 hours",
      "Established: 1947",
      "Tuition Fees: 3,47,380 RUB/year",
      "Hostel Fees: 20,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
    detailHref: "/study-destinations/study-mbbs-in-russia/immanuel-kant-baltic-federal-university",
  },
  {
    id: "kemerovo-smu",
    name: "Kemerovo State Medical University",
    cityLabel: "Kemerovo",
    location: "Kemerovo",
    population: "5,50,000 approx",
    distanceMoscow: "3,600 km",
    byAir: "4.5 hours",
    established: "1955",
    tuition: "3,50,000 RUB/year",
    hostel: "80,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Kemerovo State Medical University, established in 1955, is a specialized institution offering MBBS in Russia with strong clinical exposure. It provides modern laboratories and hands-on hospital training, making it a good option for practical medical education. Hostels are available and secure.",
    bullets: [
      "Location: Kemerovo",
      "Population: 5,50,000 approx",
      "Distance from Moscow: 3,600 km",
      "By Air: 4.5 hours",
      "Established: 1955",
      "Tuition Fees: 3,50,000 RUB/year",
      "Hostel Fees: 80,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
    detailHref: "/study-destinations/study-mbbs-in-russia/kemorovo-state-medical-university",
  },
  {
    id: "northern-arh",
    name: "Northern State Medical University",
    cityLabel: "Arkhangelsk",
    location: "Arkhangelsk",
    population: "3,50,000 approx",
    distanceMoscow: "1,200 km",
    byAir: "2 hours",
    established: "1932",
    tuition: "3,50,000 RUB/year",
    hostel: "30,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Northern State Medical University, founded in 1932, is a well-known medical institution offering MBBS abroad at moderate cost. It provides strong clinical training through affiliated hospitals and modern labs. Hostel facilities are comfortable, and the environment is safe for international students.",
    bullets: [
      "Location: Arkhangelsk",
      "Population: 3,50,000 approx",
      "Distance from Moscow: 1,200 km",
      "By Air: 2 hours",
      "Established: 1932",
      "Tuition Fees: 3,50,000 RUB/year",
      "Hostel Fees: 30,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
    detailHref: "/study-destinations/study-mbbs-in-russia/northern-state-medical-university",
  },
  {
    id: "yaroslavl",
    name: "Yaroslavl State Medical University",
    cityLabel: "Yaroslavl",
    location: "Yaroslavl",
    population: "6,00,000 approx",
    distanceMoscow: "250 km",
    byAir: "1 hour",
    established: "1944",
    tuition: "3,50,000 RUB/year",
    hostel: "90,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Yaroslavl State Medical University, established in 1944, offers quality MBBS in Russia with strong hospital exposure. It has modern laboratories and experienced faculty. The university provides safe hostels and a student-friendly environment for international students.",
    bullets: [
      "Location: Yaroslavl",
      "Population: 6,00,000 approx",
      "Distance from Moscow: 250 km",
      "By Air: 1 hour",
      "Established: 1944",
      "Tuition Fees: 3,50,000 RUB/year",
      "Hostel Fees: 90,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "ulyanovsk",
    name: "Ulyanovsk State University",
    cityLabel: "Ulyanovsk",
    location: "Ulyanovsk",
    population: "6,50,000 approx",
    distanceMoscow: "900 km",
    byAir: "1.5 hours",
    established: "1988",
    tuition: "3,50,000 RUB/year",
    hostel: "70,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Ulyanovsk State University, founded in 1988, is a modern institution offering MBBS in Russia in English medium. It provides good laboratories and clinical training in affiliated hospitals. Hostels are well-equipped, and the campus is safe for international students.",
    bullets: [
      "Location: Ulyanovsk",
      "Population: 6,50,000 approx",
      "Distance from Moscow: 900 km",
      "By Air: 1.5 hours",
      "Established: 1988",
      "Tuition Fees: 3,50,000 RUB/year",
      "Hostel Fees: 70,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
    detailHref: "/study-destinations/study-mbbs-in-russia/ulyanovsk-state-university",
  },
  {
    id: "kirov",
    name: "Kirov State Medical University",
    cityLabel: "Kirov",
    location: "Kirov",
    population: "5,00,000 approx",
    distanceMoscow: "950 km",
    byAir: "1.5 hours",
    established: "1987",
    tuition: "3,50,000 RUB/year",
    hostel: "90,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Kirov State Medical University, established in 1987, offers MBBS in Russia with strong academic and clinical training. It has well-equipped laboratories and affiliated hospitals for practical exposure. Hostels are secure and suitable for international students.",
    bullets: [
      "Location: Kirov",
      "Population: 5,00,000 approx",
      "Distance from Moscow: 950 km",
      "By Air: 1.5 hours",
      "Established: 1987",
      "Tuition Fees: 3,50,000 RUB/year",
      "Hostel Fees: 90,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "north-caucasian",
    name: "North Caucasian State Academy",
    cityLabel: "Cherkessk",
    location: "Cherkessk",
    population: "1,30,000 approx",
    distanceMoscow: "1,500 km",
    byAir: "2.5 hours",
    established: "1936",
    tuition: "3,50,000 RUB/year",
    hostel: "30,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "North Caucasian State Academy, founded in 1936, offers affordable MBBS in Russia with good academic support. It provides clinical exposure through local hospitals and basic lab facilities. Hostel accommodation is economical, and the environment is safe.",
    bullets: [
      "Location: Cherkessk",
      "Population: 1,30,000 approx",
      "Distance from Moscow: 1,500 km",
      "By Air: 2.5 hours",
      "Established: 1936",
      "Tuition Fees: 3,50,000 RUB/year",
      "Hostel Fees: 30,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
];

export const MEDIUM_TUITION_UNIVERSITIES: RussiaFeeUniversity[] = [
  {
    id: "ural",
    name: "Ural State Medical University",
    cityLabel: "Yekaterinburg",
    location: "Yekaterinburg",
    population: "15,00,000 approx",
    distanceMoscow: "1,800 km",
    byAir: "2.5 hours",
    established: "1930",
    tuition: "3,60,000 RUB/year",
    hostel: "16,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Ural State Medical University, established in 1930, is a prestigious institution offering MBBS in Russia with advanced medical training. It features modern labs and strong hospital affiliations, ensuring quality education. Hostels are affordable and well-maintained.",
    bullets: [
      "Location: Yekaterinburg",
      "Population: 15,00,000 approx",
      "Distance from Moscow: 1,800 km",
      "By Air: 2.5 hours",
      "Established: 1930",
      "Tuition Fees: 3,60,000 RUB/year",
      "Hostel Fees: 16,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
    detailHref: "/study-destinations/study-mbbs-in-russia/ural-state-medical-university",
  },
  {
    id: "altai",
    name: "Altai State Medical University",
    cityLabel: "Barnaul",
    location: "Barnaul",
    population: "6,50,000 approx",
    distanceMoscow: "3,500 km",
    byAir: "4.5 hours",
    established: "1954",
    tuition: "3,60,000 RUB/year",
    hostel: "80,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Altai State Medical University, founded in 1954, offers MBBS abroad at moderate cost with good academic infrastructure. It provides clinical training through teaching hospitals and has safe hostel facilities for international students.",
    bullets: [
      "Location: Barnaul",
      "Population: 6,50,000 approx",
      "Distance from Moscow: 3,500 km",
      "By Air: 4.5 hours",
      "Established: 1954",
      "Tuition Fees: 3,60,000 RUB/year",
      "Hostel Fees: 80,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "murmansk",
    name: "Murmansk State University",
    cityLabel: "Murmansk",
    location: "Murmansk",
    population: "3,00,000 approx",
    distanceMoscow: "2,000 km",
    byAir: "2.5 hours",
    established: "1939",
    tuition: "3,60,000 RUB/year",
    hostel: "40,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Murmansk State University, established in 1939, is located in northern Russia and offers MBBS in Russia at affordable fees. It provides basic lab facilities and hospital exposure. Hostel facilities are available, and the environment is safe and disciplined.",
    bullets: [
      "Location: Murmansk",
      "Population: 3,00,000 approx",
      "Distance from Moscow: 2,000 km",
      "By Air: 2.5 hours",
      "Established: 1939",
      "Tuition Fees: 3,60,000 RUB/year",
      "Hostel Fees: 40,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "siberian-tomsk",
    name: "Siberian State Medical University",
    cityLabel: "Tomsk",
    location: "Tomsk",
    population: "5,50,000 approx",
    distanceMoscow: "3,500 km",
    byAir: "4.5 hours",
    established: "1878",
    tuition: "3,85,600 RUB/year",
    hostel: "70,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Siberian State Medical University, founded in 1878, is one of the oldest and most prestigious institutions offering MBBS in Russia. It provides advanced laboratories and strong clinical training in hospitals, making it a top choice for quality medical education. Hostels are modern and comfortable.",
    bullets: [
      "Location: Tomsk",
      "Population: 5,50,000 approx",
      "Distance from Moscow: 3,500 km",
      "By Air: 4.5 hours",
      "Established: 1878",
      "Tuition Fees: 3,85,600 RUB/year",
      "Hostel Fees: 70,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "bashkir",
    name: "Bashkir State Medical University",
    cityLabel: "Ufa",
    location: "Ufa",
    population: "11,00,000 approx",
    distanceMoscow: "1,400 km",
    byAir: "2 hours",
    established: "1932",
    tuition: "3,99,000 RUB/year",
    hostel: "45,000 RUB/year",
    other: "25,000 RUB/year",
    description:
      "Bashkir State Medical University, established in 1932, is a leading medical university offering MBBS in Russia for Indian students. It provides excellent clinical exposure through affiliated hospitals and modern labs. Hostels are well-developed, and the campus is safe and student-friendly.",
    bullets: [
      "Location: Ufa",
      "Population: 11,00,000 approx",
      "Distance from Moscow: 1,400 km",
      "By Air: 2 hours",
      "Established: 1932",
      "Tuition Fees: 3,99,000 RUB/year",
      "Hostel Fees: 45,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
    detailHref: "/study-destinations/study-mbbs-in-russia/bashkir-medical-university",
  },
  {
    id: "tambov",
    name: "Tambov State University",
    cityLabel: "Tambov",
    location: "Tambov",
    population: "3,00,000 approx",
    distanceMoscow: "480 km",
    byAir: "1 hour",
    established: "1918",
    tuition: "4,10,000 RUB/year",
    hostel: "Included",
    other: "25,000 RUB/year",
    bullets: [
      "Location: Tambov",
      "Population: 3,00,000 approx",
      "Distance from Moscow: 480 km",
      "By Air: 1 hour",
      "Established: 1918",
      "Tuition Fees: 4,10,000 RUB/year",
      "Hostel Fees: Included",
      "Other Charges: 25,000 RUB/year",
    ],
    detailHref: "/study-destinations/study-mbbs-in-russia/tambov-state-university",
  },
  {
    id: "tver",
    name: "Tver State Medical University",
    cityLabel: "Tver",
    location: "Tver",
    population: "4,00,000 approx",
    distanceMoscow: "180 km",
    byAir: "1 hour",
    established: "1936",
    tuition: "4,30,000 RUB/year",
    hostel: "80,000 RUB/year",
    other: "25,000 RUB/year",
    bullets: [
      "Location: Tver",
      "Population: 4,00,000 approx",
      "Distance from Moscow: 180 km",
      "By Air: 1 hour",
      "Established: 1936",
      "Tuition Fees: 4,30,000 RUB/year",
      "Hostel Fees: 80,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "samara",
    name: "Samara State Medical University",
    cityLabel: "Samara",
    location: "Samara",
    population: "11,00,000 approx",
    distanceMoscow: "1,000 km",
    byAir: "1.5 hours",
    established: "1919",
    tuition: "4,50,000 RUB/year",
    hostel: "32,000 RUB/year",
    other: "25,000 RUB/year",
    bullets: [
      "Location: Samara",
      "Population: 11,00,000 approx",
      "Distance from Moscow: 1,000 km",
      "By Air: 1.5 hours",
      "Established: 1919",
      "Tuition Fees: 4,50,000 RUB/year",
      "Hostel Fees: 32,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
];

export const HIGH_TUITION_UNIVERSITIES: RussiaFeeUniversity[] = [
  {
    id: "privolzhsky",
    name: "Privolzhsky Research Medical University",
    cityLabel: "Nizhny Novgorod",
    location: "Nizhny Novgorod",
    population: "12,00,000 approx",
    distanceMoscow: "400 km",
    byAir: "1 hour",
    established: "1920",
    tuition: "4,60,000 RUB/year",
    hostel: "1,20,000 RUB/year",
    other: "25,000 RUB/year",
    bullets: [
      "Location: Nizhny Novgorod",
      "Population: 12,00,000 approx",
      "Distance from Moscow: 400 km",
      "By Air: 1 hour",
      "Established: 1920",
      "Tuition Fees: 4,60,000 RUB/year",
      "Hostel Fees: 1,20,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "volgograd",
    name: "Volgograd State Medical University",
    cityLabel: "Volgograd",
    location: "Volgograd",
    population: "10,00,000 approx",
    distanceMoscow: "970 km",
    byAir: "1.5 hours",
    established: "1935",
    tuition: "4,80,000 RUB/year",
    hostel: "60,000 RUB/year",
    other: "25,000 RUB/year",
    bullets: [
      "Location: Volgograd",
      "Population: 10,00,000 approx",
      "Distance from Moscow: 970 km",
      "By Air: 1.5 hours",
      "Established: 1935",
      "Tuition Fees: 4,80,000 RUB/year",
      "Hostel Fees: 60,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "kuban",
    name: "Kuban State Medical University",
    cityLabel: "Krasnodar",
    location: "Krasnodar",
    population: "10,00,000 approx",
    distanceMoscow: "1,350 km",
    byAir: "2 hours",
    established: "1920",
    tuition: "4,82,000 RUB/year",
    hostel: "80,000 RUB/year",
    other: "25,000 RUB/year",
    bullets: [
      "Location: Krasnodar",
      "Population: 10,00,000 approx",
      "Distance from Moscow: 1,350 km",
      "By Air: 2 hours",
      "Established: 1920",
      "Tuition Fees: 4,82,000 RUB/year",
      "Hostel Fees: 80,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "fefu",
    name: "Far Eastern Federal University",
    cityLabel: "Vladivostok",
    location: "Vladivostok",
    population: "6,00,000 approx",
    distanceMoscow: "9,000 km",
    byAir: "8–9 hours",
    established: "1899",
    tuition: "4,95,000 RUB/year",
    hostel: "50,000 RUB/year",
    other: "25,000 RUB/year",
    bullets: [
      "Location: Vladivostok",
      "Population: 6,00,000 approx",
      "Distance from Moscow: 9,000 km",
      "By Air: 8–9 hours",
      "Established: 1899",
      "Tuition Fees: 4,95,000 RUB/year",
      "Hostel Fees: 50,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "mephi-obninsk",
    name: "MEPhI Obninsk Branch",
    cityLabel: "Obninsk",
    location: "Obninsk",
    population: "1,20,000 approx",
    distanceMoscow: "100 km",
    byAir: "1 hour",
    established: "1953",
    tuition: "5,10,000 RUB/year",
    hostel: "14,000 RUB/year",
    other: "25,000 RUB/year",
    bullets: [
      "Location: Obninsk",
      "Population: 1,20,000 approx",
      "Distance from Moscow: 100 km",
      "By Air: 1 hour",
      "Established: 1953",
      "Tuition Fees: 5,10,000 RUB/year",
      "Hostel Fees: 14,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
    detailHref: "/study-destinations/study-mbbs-in-russia/mephi",
  },
  {
    id: "mari",
    name: "Mari State University",
    cityLabel: "Yoshkar-Ola",
    location: "Yoshkar-Ola",
    population: "3,00,000 approx",
    distanceMoscow: "750 km",
    byAir: "1.5 hours",
    established: "1972",
    tuition: "5,40,000 RUB/year",
    hostel: "Included",
    other: "25,000 RUB/year",
    bullets: [
      "Location: Yoshkar-Ola",
      "Population: 3,00,000 approx",
      "Distance from Moscow: 750 km",
      "By Air: 1.5 hours",
      "Established: 1972",
      "Tuition Fees: 5,40,000 RUB/year",
      "Hostel Fees: Included",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "nwsmu",
    name: "North-Western State Medical University",
    cityLabel: "Saint Petersburg",
    location: "Saint Petersburg",
    population: "50,00,000+",
    distanceMoscow: "700 km",
    byAir: "1.5 hours",
    established: "1907",
    tuition: "5,50,000 RUB/year",
    hostel: "42,000 RUB/year",
    other: "25,000 RUB/year",
    bullets: [
      "Location: Saint Petersburg",
      "Population: 50,00,000+",
      "Distance from Moscow: 700 km",
      "By Air: 1.5 hours",
      "Established: 1907",
      "Tuition Fees: 5,50,000 RUB/year",
      "Hostel Fees: 42,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
    detailHref: "/study-destinations/study-mbbs-in-russia/north-western-state-medical-university",
  },
  {
    id: "synergy",
    name: "Synergy University",
    cityLabel: "Moscow",
    location: "Moscow",
    population: "1,30,00,000+",
    distanceMoscow: "—",
    byAir: "Direct",
    established: "1995",
    tuition: "5,80,000 RUB/year",
    hostel: "1,30,000 RUB/year",
    other: "25,000 RUB/year",
    bullets: [
      "Location: Moscow",
      "Population: 1,30,00,000+",
      "By Air: Direct",
      "Established: 1995",
      "Tuition Fees: 5,80,000 RUB/year",
      "Hostel Fees: 1,30,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "kazan-smu",
    name: "Kazan State Medical University",
    cityLabel: "Kazan",
    location: "Kazan",
    population: "12,00,000 approx",
    distanceMoscow: "820 km",
    byAir: "1.5 hours",
    established: "1814",
    tuition: "6,00,000 RUB/year",
    hostel: "80,000 RUB/year",
    other: "25,000 RUB/year",
    bullets: [
      "Location: Kazan",
      "Population: 12,00,000 approx",
      "Distance from Moscow: 820 km",
      "By Air: 1.5 hours",
      "Established: 1814",
      "Tuition Fees: 6,00,000 RUB/year",
      "Hostel Fees: 80,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
  },
  {
    id: "mephi-moscow",
    name: "MEPhI Moscow Branch",
    cityLabel: "Moscow",
    location: "Moscow",
    population: "1,30,00,000+",
    distanceMoscow: "—",
    byAir: "Direct",
    established: "1942",
    tuition: "6,57,360 RUB/year",
    hostel: "20,000 RUB/year",
    other: "25,000 RUB/year",
    bullets: [
      "Location: Moscow",
      "Population: 1,30,00,000+",
      "By Air: Direct",
      "Established: 1942",
      "Tuition Fees: 6,57,360 RUB/year",
      "Hostel Fees: 20,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
    detailHref: "/study-destinations/study-mbbs-in-russia/mephi",
  },
  {
    id: "kfu",
    name: "Kazan Federal University",
    cityLabel: "Kazan",
    location: "Kazan",
    population: "12,00,000 approx",
    distanceMoscow: "820 km",
    byAir: "1.5 hours",
    established: "1804",
    tuition: "6,60,000 RUB/year",
    hostel: "25,000 RUB/year",
    other: "25,000 RUB/year",
    bullets: [
      "Location: Kazan",
      "Population: 12,00,000 approx",
      "Distance from Moscow: 820 km",
      "By Air: 1.5 hours",
      "Established: 1804",
      "Tuition Fees: 6,60,000 RUB/year",
      "Hostel Fees: 25,000 RUB/year",
      "Other Charges: 25,000 RUB/year",
    ],
    detailHref: "/study-destinations/study-mbbs-in-russia/kazan-federal-university",
  },
];
